version: "3.5"

services:
  cardano-node:
    image: inputoutput/cardano-node:${NODE}
    environment:
      NETWORK:
    volumes:
      - node-db:/data
      - node-ipc:/ipc
      - ${NODE_CONFIG_PATH}:/config
    command: run --socket-path /ipc/node.socket --config /config/*-config.json --topology /config/*-topology.json --database-path /data
    restart: on-failure

  cardano-wallet:
    image: inputoutput/cardano-wallet:${WALLET}
    volumes:
      - wallet-shelley-db:/wallet-db
      - node-ipc:/ipc
      - ${NODE_CONFIG_PATH}:/config
    ports:
      - 8090:8090
    command: serve --testnet /config/*-genesis.json --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0
    restart: on-failure

volumes:
  node-db:
  wallet-shelley-db:
  node-ipc:
