name: Nightly Windows

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node db
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.NODE_DB }}
        key: ${{ runner.os }}-node-db-nightly-win-tests-${{ hashFiles('**/protocolMagicId') }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install dependencies
      run: bundle install

    - name: Prepare Windows
      run: |
        choco install wget
        choco install unzip
        choco install nssm

    - name: Get cardano-wallet and cardano-node
      run: |
        wget ${env:LATEST_WIN_BIN}
        unzip binary-dist
        dir

    - name: Display versions
      run: |
        "cardano-wallet.exe version" | cmd
        "cardano-node.exe version" | cmd

    - name: Start cardano-wallet and cardano-node
      run: |
        bundle exec rake wget_configs["testnet"]
        bundle exec rake win_setup_node_and_wallet

    - name: Wait until node is synced
      run: bundle exec rake wait_until_node_synced

    - name: Run all tests
      run: bundle exec rspec .

    - name: Cleanup
      run: bundle exec rake win_remove_nssm_services

    env:
      LATEST_WIN_BIN: https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-win64/latest/download-by-type/file/binary-dist
      NODE_DB: d:\node-db-nightly-win-tests
      WALLET_DB: d:\wallet-db
      TOKEN_METADATA: http://metadata-server-mock.herokuapp.com/
