name: Nightly

on:
  schedule:
  - cron:  "0 23 * * *"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up cardano-wallet
      run: NODE_CONFIG_PATH=`pwd`/spec/testnet docker-compose -f docker-compose-shelley.yml up --detach
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Wait until node is synced
      run: bundle exec rake wait_until_node_synced
    - name: Run all tests
      run: bundle exec rspec .
    env:
      CI: true
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NETWORK: testnet
      WALLET: dev-master-shelley
      NODE: 1.20.0
