name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install dependencies
      run: bundle install

    - name: Run rubocop
      run: rubocop

    - name: Get recent configs
      run: bundle exec rake get_latest_configs[$NETWORK]

    - name: Set up cardano-wallet and cardano-node
      run: |
        echo "Wallet: $WALLET"
        echo "Node: $NODE"
        NODE_CONFIG_PATH=`pwd`/configs docker-compose up --detach
        docker run --rm inputoutput/cardano-wallet:$WALLET version
        docker run --rm inputoutput/cardano-node:$NODE cli version
        ls ~/node-db-nightly-docker

    - name: Run all tests except nighlty
      run: rake spec

    - name: Stop docker-compose
      run: NODE_CONFIG_PATH=`pwd`/configs docker-compose down
    env:
      CI: true
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NETWORK: preview
      WALLET: dev-master
      NODE: 1.35.3
