# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up cardano-wallet
      run: NODE_CONFIG_PATH=`pwd`/spec/testnet docker-compose -f docker-compose-shelley.yml up --detach
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: bundle install
    - name: Run all tests except nighlty
      run: bundle exec rspec . -t ~nightly
    env:
      CI: true
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NETWORK: testnet
      WALLET: dev-master-shelley
      NODE: 1.24.2
